#!/bin/bash
# requires jq
# Author: https://github.com/BelkaDev

urlencode() {
echo ${1// /"%20"}
}

#settings
lang="en"
limit=6
#######

url="https://$lang.wikipedia.org/w/api.php?action=query&format=json&generator=prefixsearch&prop=pageprops|pageimages|description&redirects=&ppprop=displaytitle&piprop=thumbnail&pithumbsize=80&pilimit=6&gpssearch=$(urlencode "$*")&gpsnamespace=0&gpslimit=$limit"
res=$(jq -r '.query["pages"][]  | "\(.title) - \(.description) \(.pageid)"'  <<< "$(curl -s "$url" &)" | tr -d '"')
echo "$res"
